const requestIdHeader = {
    description:
        "Optional opaque request identifier. If omitted, LogForge generates a UUID.",
    schema: {
        type: "string",
        maxLength: 128,
    },
};

const requestIdResponseHeader = {
    description:
        "Request identifier supplied by the client or generated by LogForge.",
    schema: {
        type: "string",
    },
};

const logLevel = {
    type: "string",
    enum: ["INFO", "WARN", "ERROR"],
};

const logSchema = {
    type: "object",
    required: ["id", "timestamp", "level", "message", "createdAt"],
    properties: {
        id: {
            type: "string",
            format: "uuid",
        },
        timestamp: {
            type: "string",
            format: "date-time",
        },
        level: logLevel,
        message: {
            type: "string",
            minLength: 1,
            description: "A non-empty message. Leading and trailing whitespace is trimmed.",
        },
        createdAt: {
            type: "string",
            format: "date-time",
        },
    },
};

const createLogSchema = {
    type: "object",
    required: ["timestamp", "level", "message"],
    properties: {
        timestamp: {
            type: "string",
            format: "date-time",
            description: "A timestamp accepted by JavaScript Date parsing.",
        },
        level: logLevel,
        message: {
            type: "string",
            minLength: 1,
            description: "A non-empty message. Leading and trailing whitespace is trimmed.",
        },
    },
};

const paginationSchema = {
    type: "object",
    required: ["page", "limit", "total", "totalPages"],
    properties: {
        page: { type: "integer", minimum: 1 },
        limit: { type: "integer", minimum: 1, maximum: 100 },
        total: { type: "integer", minimum: 0 },
        totalPages: { type: "integer", minimum: 0 },
    },
};

const errorSchema = {
    type: "object",
    required: ["success", "error"],
    properties: {
        success: { type: "boolean", enum: [false] },
        error: {
            type: "object",
            required: ["message", "requestId"],
            properties: {
                message: { type: "string" },
                code: { type: "string" },
                details: {
                    description: "Validation or application-specific error details.",
                    nullable: true,
                },
                requestId: {
                    type: "string",
                    description: "Request identifier for correlating the response with the request.",
                },
            },
        },
    },
};

const requestBody = (schema: unknown, description: string) => ({
    required: true,
    description,
    content: {
        "application/json": {
            schema,
        },
    },
});

const jsonResponse = (
    description: string,
    schema: unknown,
    headers = true,
) => ({
    description,
    headers: headers ? { "X-Request-Id": { $ref: "#/components/headers/X-Request-Id" } } : undefined,
    content: {
        "application/json": {
            schema,
        },
    },
});

const errorResponse = (description: string) => ({
    description,
    headers: {
        "X-Request-Id": { $ref: "#/components/headers/X-Request-Id" },
    },
    content: {
        "application/json": {
            schema: { $ref: "#/components/schemas/ErrorResponse" },
        },
    },
});

const successEnvelope = (data: unknown) => ({
    type: "object",
    required: ["success", "data"],
    properties: {
        success: { type: "boolean", enum: [true] },
        data,
    },
});

const openApiDocument = {
    openapi: "3.0.3",
    info: {
        title: "LogForge API",
        version: "1.0.0",
        description: "HTTP API for ingesting, querying, and analyzing application logs.",
    },
    servers: [{ url: "/", description: "Current LogForge server" }],
    tags: [{ name: "Health" }, { name: "Logs" }],
    paths: {
        "/health": {
            get: {
                tags: ["Health"],
                summary: "Check API health",
                parameters: [{ name: "X-Request-Id", in: "header", ...requestIdHeader }],
                responses: {
                    200: jsonResponse(
                        "The service is healthy.",
                        {
                            type: "object",
                            required: ["status", "service"],
                            properties: {
                                status: { type: "string", enum: ["ok"] },
                                service: { type: "string", enum: ["LogForge"] },
                            },
                        },
                    ),
                    500: errorResponse("Unexpected server error."),
                },
            },
        },
        "/api/logs": {
            post: {
                tags: ["Logs"],
                summary: "Create a log",
                parameters: [{ name: "X-Request-Id", in: "header", ...requestIdHeader }],
                requestBody: requestBody({ $ref: "#/components/schemas/CreateLog" }, "Log to create."),
                responses: {
                    201: jsonResponse("The log was created.", successEnvelope({ $ref: "#/components/schemas/Log" })),
                    400: errorResponse("The log data is invalid. Validation details are included."),
                    500: errorResponse("Unexpected server error."),
                },
            },
            get: {
                tags: ["Logs"],
                summary: "List logs",
                parameters: [
                    { name: "X-Request-Id", in: "header", ...requestIdHeader },
                    { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } },
                    { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } },
                    { name: "level", in: "query", description: "Case-insensitive log level filter.", schema: logLevel },
                    { name: "search", in: "query", schema: { type: "string", description: "Case-insensitive message search." } },
                    { name: "from", in: "query", schema: { type: "string", format: "date-time" } },
                    { name: "to", in: "query", schema: { type: "string", format: "date-time" } },
                ],
                responses: {
                    200: jsonResponse("A paginated list of logs.", {
                        type: "object",
                        required: ["success", "data", "pagination"],
                        properties: {
                            success: { type: "boolean", enum: [true] },
                            data: { type: "array", items: { $ref: "#/components/schemas/Log" } },
                            pagination: { $ref: "#/components/schemas/Pagination" },
                        },
                    }),
                    400: errorResponse("The query parameters are invalid."),
                    500: errorResponse("Unexpected server error."),
                },
            },
        },
        "/api/logs/bulk": {
            post: {
                tags: ["Logs"],
                summary: "Create multiple logs",
                parameters: [{ name: "X-Request-Id", in: "header", ...requestIdHeader }],
                requestBody: requestBody({ $ref: "#/components/schemas/BulkCreateLogs" }, "One to 100 logs to create."),
                responses: {
                    201: jsonResponse("The logs were created.", successEnvelope({
                        type: "object",
                        required: ["created"],
                        properties: { created: { type: "integer", minimum: 0 } },
                    })),
                    400: errorResponse("The bulk log data is invalid. Validation details are included."),
                    500: errorResponse("Unexpected server error."),
                },
            },
        },
        "/api/logs/stats": {
            get: {
                tags: ["Logs"],
                summary: "Get log statistics",
                parameters: [
                    { name: "X-Request-Id", in: "header", ...requestIdHeader },
                    { name: "from", in: "query", schema: { type: "string", format: "date-time" } },
                    { name: "to", in: "query", schema: { type: "string", format: "date-time" } },
                ],
                responses: {
                    200: jsonResponse("Log counts grouped by level.", successEnvelope({ $ref: "#/components/schemas/Stats" })),
                    400: errorResponse("The query parameters are invalid."),
                    500: errorResponse("Unexpected server error."),
                },
            },
        },
        "/api/logs/{id}": {
            parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
            get: {
                tags: ["Logs"],
                summary: "Get a log by ID",
                parameters: [{ name: "X-Request-Id", in: "header", ...requestIdHeader }],
                responses: {
                    200: jsonResponse("The requested log.", successEnvelope({ $ref: "#/components/schemas/Log" })),
                    404: errorResponse("The log was not found."),
                    500: errorResponse("Unexpected server error."),
                },
            },
            delete: {
                tags: ["Logs"],
                summary: "Delete a log by ID",
                parameters: [{ name: "X-Request-Id", in: "header", ...requestIdHeader }],
                responses: {
                    200: jsonResponse("The log was deleted.", successEnvelope({
                        type: "object",
                        required: ["message"],
                        properties: { message: { type: "string", enum: ["Log deleted successfully"] } },
                    })),
                    404: errorResponse("The log was not found."),
                    500: errorResponse("Unexpected server error."),
                },
            },
        },
    },
    components: {
        headers: {
            "X-Request-Id": requestIdResponseHeader,
        },
        schemas: {
            LogLevel: logLevel,
            Log: logSchema,
            CreateLog: createLogSchema,
            BulkCreateLogs: {
                type: "object",
                required: ["logs"],
                properties: {
                    logs: {
                        type: "array",
                        minItems: 1,
                        maxItems: 100,
                        items: { $ref: "#/components/schemas/CreateLog" },
                    },
                },
            },
            Pagination: paginationSchema,
            Stats: {
                type: "object",
                required: ["totalLogs", "byLevel"],
                properties: {
                    totalLogs: { type: "integer", minimum: 0 },
                    byLevel: {
                        type: "object",
                        required: ["INFO", "WARN", "ERROR"],
                        properties: {
                            INFO: { type: "integer", minimum: 0 },
                            WARN: { type: "integer", minimum: 0 },
                            ERROR: { type: "integer", minimum: 0 },
                        },
                    },
                },
            },
            ErrorResponse: errorSchema,
        },
    },
};

export default openApiDocument;
